# Generated by Django 5.2.16 on 2026-07-16 06:32

from django.db import migrations, models


def backfill_blank_emails(apps, schema_editor):
    """
    Existing seeded users (e.g. fleet2, driver1) have blank '' emails.
    Two blank strings would collide once email becomes unique, so give any
    blank-email user a placeholder based on their username first.
    Safe no-op if there are no such users.
    """
    User = apps.get_model('core', 'User')
    for user in User.objects.filter(email=''):
        user.email = f'{user.username}@placeholder.local'
        user.save(update_fields=['email'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_blank_emails, noop_reverse),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
